// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChjY71eQjvjEQx_Pl3H5dBBqkxDfIDhJo',
    appId: '1:944199132408:web:c46dd1ce361786a1c8c70d',
    messagingSenderId: '944199132408',
    projectId: 'tanavue-database',
    authDomain: 'tanavue-database.firebaseapp.com',
    databaseURL: 'https://tanavue-database-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tanavue-database.firebasestorage.app',
    measurementId: 'G-C56H04YLMP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSdGeAwQyS-a9YZHvyMAXdqWApyOsYdOU',
    appId: '1:944199132408:android:32bf0bab4aae5af8c8c70d',
    messagingSenderId: '944199132408',
    projectId: 'tanavue-database',
    databaseURL: 'https://tanavue-database-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tanavue-database.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJ085Sa3e2zh9CL7KQWY-odgGJmHd5mDw',
    appId: '1:944199132408:ios:e5a50e98b8c6e3f7c8c70d',
    messagingSenderId: '944199132408',
    projectId: 'tanavue-database',
    databaseURL: 'https://tanavue-database-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tanavue-database.firebasestorage.app',
    iosBundleId: 'com.example.tanavue',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJ085Sa3e2zh9CL7KQWY-odgGJmHd5mDw',
    appId: '1:944199132408:ios:e5a50e98b8c6e3f7c8c70d',
    messagingSenderId: '944199132408',
    projectId: 'tanavue-database',
    databaseURL: 'https://tanavue-database-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tanavue-database.firebasestorage.app',
    iosBundleId: 'com.example.tanavue',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChjY71eQjvjEQx_Pl3H5dBBqkxDfIDhJo',
    appId: '1:944199132408:web:c46dd1ce361786a1c8c70d',
    messagingSenderId: '944199132408',
    projectId: 'tanavue-database',
    authDomain: 'tanavue-database.firebaseapp.com',
    databaseURL: 'https://tanavue-database-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tanavue-database.firebasestorage.app',
    measurementId: 'G-C56H04YLMP',
  );
}
